// license-hashgen generates embedded file hashes for the integrity check system.
// Run this after modifying any critical source files:
//
//	cd frp-panel-licensed
//	go run ./cmd/license-hashgen/
package main

import (
	"crypto/md5"
	"fmt"
	"os"
	"strings"
	"text/template"
)

// criticalFiles lists files whose modification should be detected.
var criticalFiles = []string{
	"cmd/panel/main.go",
	"internal/api/router.go",
	"internal/api/middleware/auth.go",
	"internal/api/middleware/license.go",
	"internal/pkg/license/license.go",
	"internal/pkg/license/integrity.go",
	"internal/pkg/license/crypto.go",
}

const outputTemplate = `// Code generated by license-hashgen; DO NOT EDIT.
package license

func init() {
	// Update embedded hashes with current file checksums.
	// This makes it harder to tamper with the license system.
	{{- range $file, $hash := .}}
	embeddedHashes["{{ $file }}"] = "{{ $hash }}"
	{{- end }}
}
`

func main() {
	hashes := make(map[string]string)

	for _, file := range criticalFiles {
		data, err := os.ReadFile(file)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: cannot read %s: %v (skipping)\n", file, err)
			// Use placeholder - will fail integrity check if file is modified
			hashes[file] = "NEEDS_REGENERATION"
			continue
		}
		h := md5.Sum(data)
		hashes[file] = fmt.Sprintf("%x", h)
		fmt.Printf("%s: %x\n", file, h)
	}

	// Generate Go source file
	tmpl, err := template.New("hashes").Parse(outputTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "template error: %v\n", err)
		os.Exit(1)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, hashes); err != nil {
		fmt.Fprintf(os.Stderr, "execute error: %v\n", err)
		os.Exit(1)
	}

	outputFile := "internal/pkg/license/hashes_generated.go"
	if err := os.WriteFile(outputFile, []byte(buf.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("\nGenerated %s with %d hashes\n", outputFile, len(hashes))
}
