package frpconfig

import (
	"bytes"
	"fmt"
	"strconv"
	"text/template"

	"github.com/frp-panel/frp-panel/internal/model"
)

type FrpcConfig struct {
	ServerAddr string        `json:"serverAddr"`
	ServerPort int           `json:"serverPort"`
	ServerID   uint          `json:"serverId"`
	APIKey     string        `json:"apiKey"`
	Proxies    []ProxyConfig `json:"proxies"`
}

type ProxyConfig struct {
	Name           string   `json:"name"`
	Type           string   `json:"type"`
	LocalIP        string   `json:"localIP"`
	LocalPort      int      `json:"localPort"`
	RemotePort     int      `json:"remotePort,omitempty"`
	CustomDomains  []string `json:"customDomains,omitempty"`
	Subdomain      string   `json:"subdomain,omitempty"`
	SecretKey      string   `json:"secretKey,omitempty"`
	UseEncryption  bool     `json:"useEncryption,omitempty"`
	UseCompression bool     `json:"useCompression,omitempty"`
	BandwidthLimit int64    `json:"bandwidthLimit,omitempty"`
}

const frpcTomlTemplate = `# Generated by frp-panel
serverAddr = {{quote .ServerAddr}}
serverPort = {{.ServerPort}}

[auth]
method = "token"
token = {{quote .APIKey}}

[transport]
tcpMux = true

[metadatas]
apikey = {{quote .APIKey}}
server_id = {{quote (printf "%d" .ServerID)}}

{{range .Proxies}}
[[proxies]]
name = {{quote .Name}}
type = {{quote .Type}}
localIP = {{quote .LocalIP}}
localPort = {{.LocalPort}}
{{if .RemotePort}}
remotePort = {{.RemotePort}}
{{end}}
{{if .CustomDomains}}
customDomains = [{{range $i, $d := .CustomDomains}}{{if $i}}, {{end}}{{quote $d}}{{end}}]
{{end}}
{{if .Subdomain}}
subdomain = {{quote .Subdomain}}
{{end}}
{{if .SecretKey}}
secretKey = {{quote .SecretKey}}
{{end}}
{{if .UseEncryption}}
transport.useEncryption = true
{{end}}
{{if .UseCompression}}
transport.useCompression = true
{{end}}
{{if .BandwidthLimit}}
transport.bandwidthLimit = "{{FormatBandwidth .BandwidthLimit}}"
{{end}}
{{end}}
`

func FormatBandwidth(bytes int64) string {
	if bytes <= 0 {
		return ""
	}
	if bytes >= 1024*1024*1024 {
		return fmt.Sprintf("%d GB", bytes/(1024*1024*1024))
	}
	if bytes >= 1024*1024 {
		return fmt.Sprintf("%d MB", bytes/(1024*1024))
	}
	if bytes >= 1024 {
		return fmt.Sprintf("%d KB", bytes/1024)
	}
	return fmt.Sprintf("%d B", bytes)
}

func GenerateFrpcConfig(server *model.Server, user *model.User, proxies []model.Proxy) (string, error) {
	config, err := BuildFrpcConfig(server, user, proxies)
	if err != nil {
		return "", err
	}

	funcMap := template.FuncMap{
		"FormatBandwidth": FormatBandwidth,
		"quote":           strconv.Quote,
	}

	tmpl, err := template.New("frpc").Funcs(funcMap).Parse(frpcTomlTemplate)
	if err != nil {
		return "", fmt.Errorf("template parse error: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, config); err != nil {
		return "", fmt.Errorf("template execute error: %w", err)
	}

	return buf.String(), nil
}

func BuildFrpcConfig(server *model.Server, user *model.User, proxies []model.Proxy) (*FrpcConfig, error) {
	// The client authenticates with its own API key. The FRPS plugin replaces
	// the login digest with the node token after checking node access.
	apiKey := user.APIKey
	if apiKey == "" {
		return nil, fmt.Errorf("user API key is empty")
	}

	config := &FrpcConfig{
		ServerAddr: server.IP,
		ServerPort: server.BindPort,
		ServerID:   server.ID,
		APIKey:     apiKey,
	}

	for _, proxy := range proxies {
		proxyCfg := ProxyConfig{
			Name:           proxy.Name,
			Type:           proxy.Type,
			LocalIP:        proxy.LocalIP,
			LocalPort:      proxy.LocalPort,
			RemotePort:     proxy.RemotePort,
			Subdomain:      proxy.Subdomain,
			SecretKey:      proxy.SecretKey,
			UseEncryption:  proxy.UseEncryption,
			UseCompression: proxy.UseCompression,
			BandwidthLimit: proxy.BandwidthLimit,
		}

		// Parse custom domains
		if proxy.CustomDomains != "" {
			// Simple parsing - assume comma-separated or JSON array
			proxyCfg.CustomDomains = parseCustomDomains(proxy.CustomDomains)
		}

		config.Proxies = append(config.Proxies, proxyCfg)
	}
	return config, nil
}

func parseCustomDomains(s string) []string {
	if s == "" {
		return nil
	}

	// Try to parse as JSON array
	if s[0] == '[' {
		var domains []string
		// Simple JSON array parsing
		s = s[1 : len(s)-1]
		for _, d := range splitAndTrim(s, ",") {
			d = trimQuotes(d)
			if d != "" {
				domains = append(domains, d)
			}
		}
		return domains
	}

	// Parse as comma-separated
	return splitAndTrim(s, ",")
}

func splitAndTrim(s, sep string) []string {
	var result []string
	for _, part := range split(s, sep) {
		part = trimSpaces(part)
		if part != "" {
			result = append(result, part)
		}
	}
	return result
}

func split(s, sep string) []string {
	if s == "" {
		return nil
	}
	var result []string
	start := 0
	for i := 0; i < len(s); i++ {
		if string(s[i]) == sep {
			result = append(result, s[start:i])
			start = i + 1
		}
	}
	result = append(result, s[start:])
	return result
}

func trimSpaces(s string) string {
	start := 0
	end := len(s)
	for start < end && s[start] == ' ' {
		start++
	}
	for end > start && s[end-1] == ' ' {
		end--
	}
	return s[start:end]
}

func trimQuotes(s string) string {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	if len(s) >= 2 && s[0] == '\'' && s[len(s)-1] == '\'' {
		return s[1 : len(s)-1]
	}
	return s
}
