// Code generated by license-hashgen; DO NOT EDIT.
package license

func init() {
	// Update embedded hashes with current file checksums.
	// This makes it harder to tamper with the license system.
	embeddedHashes["cmd/panel/main.go"] = "edc20eb4820658d63a9a75c4994e27b9"
	embeddedHashes["internal/api/middleware/auth.go"] = "37cc542dcb4d1473aa7a0e2ddb65caa5"
	embeddedHashes["internal/api/middleware/license.go"] = "2b2aa2dcaf8e0907f25c2fb2ddce968e"
	embeddedHashes["internal/api/router.go"] = "900f6574156fe6225868e1bb76679f42"
	embeddedHashes["internal/pkg/license/crypto.go"] = "33841a43bc95a5fc08c2545acc186221"
	embeddedHashes["internal/pkg/license/integrity.go"] = "7810af815d4d0b4aa73366d6490f4684"
	embeddedHashes["internal/pkg/license/license.go"] = "2f8054eed0a4ee5562139974f367a86e"
}
