package deployer

import (
	"bytes"
	"fmt"
	"log"
	"net/url"
	"regexp"
	"strings"
	"text/template"
	"time"

	"github.com/frp-panel/frp-panel/internal/model"
	"github.com/frp-panel/frp-panel/internal/pkg/hash"
	"github.com/frp-panel/frp-panel/internal/pkg/sshpool"
	"gorm.io/gorm"
)

type Deployer struct {
	db               *gorm.DB
	pool             *sshpool.Pool
	pluginWebhookURL string
	githubMirror     string
	panelPort        int // actual port the panel is listening on
}

func New(db *gorm.DB, pluginWebhookURL string, githubMirror string, panelPort int) *Deployer {
	return &Deployer{
		db:               db,
		pool:             sshpool.NewPool(),
		pluginWebhookURL: pluginWebhookURL,
		githubMirror:     githubMirror,
		panelPort:        panelPort,
	}
}

type FrpsConfig struct {
	BindAddr          string
	BindPort          int
	Token             string
	VhostHTTPPort     int
	VhostHTTPSPort    int
	SubdomainHost     string
	DashboardAddr     string
	DashboardPort     int
	DashboardUser     string
	DashboardPassword string
	PluginAddr        string
	PluginPath        string
	MaxPoolCount      int
	LogFile           string
}

const frpsTomlTemplate = `# Generated by frp-panel
bindAddr = "{{.BindAddr}}"
bindPort = {{.BindPort}}

{{if .Token}}
[auth]
method = "token"
token = "{{.Token}}"
{{end}}

{{if .VhostHTTPPort}}
vhostHTTPPort = {{.VhostHTTPPort}}
{{end}}

{{if .VhostHTTPSPort}}
vhostHTTPSPort = {{.VhostHTTPSPort}}
{{end}}

{{if .SubdomainHost}}
subDomainHost = "{{.SubdomainHost}}"
{{end}}

[webServer]
addr = "0.0.0.0"
port = {{.DashboardPort}}
user = "{{.DashboardUser}}"
password = "{{.DashboardPassword}}"

{{if .PluginAddr}}
[[httpPlugins]]
name = "frp-panel"
addr = "{{.PluginAddr}}"
path = "{{.PluginPath}}"
ops = ["Login", "NewProxy", "CloseProxy", "Ping"]
tlsVerify = true
{{end}}

[transport]
tcpMux = true
maxPoolCount = 10

[log]
to = "{{.LogFile}}"
level = "info"
maxDays = 7
`

const frpsServiceTemplate = `[Unit]
Description=frps server
After=network.target

[Service]
Type=simple
ExecStart=/opt/frp/frps -c /opt/frp/frps.toml
Restart=on-failure
RestartSec=5
LimitNOFILE=1048576

[Install]
WantedBy=multi-user.target
`

const frpsOpenRCTemplate = `#!/sbin/openrc-run
name="frps server"
description="FRP server"
command="/opt/frp/frps"
command_args="-c /opt/frp/frps.toml"
command_background="yes"
pidfile="/run/frps.pid"
output_log="/var/log/frps-service.log"
error_log="/var/log/frps-service.log"

depend() {
  need net
}
`

const installScriptTemplate = `#!/bin/sh
set -eu

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

if [ "$(id -u)" -ne 0 ]; then
  fail "deployment requires root privileges"
fi

if ! command -v systemctl >/dev/null 2>&1 && ! command -v rc-service >/dev/null 2>&1; then
  fail "a supported service manager is required (systemd or OpenRC)"
fi

echo "=== Detecting system info ==="
ARCH=$(uname -m)
case $ARCH in
  x86_64)  ARCH="amd64" ;;
  aarch64) ARCH="arm64" ;;
  armv7l)  ARCH="arm" ;;
  *)       echo "Unsupported arch: $ARCH"; exit 1 ;;
esac
OS="linux"
echo "Architecture: $ARCH, OS: $OS"

has_downloader() {
  command -v curl >/dev/null 2>&1 || command -v wget >/dev/null 2>&1 || command -v python3 >/dev/null 2>&1
}

install_dependencies() {
  echo "=== Installing required dependencies ==="
  if command -v apt-get >/dev/null 2>&1; then
    DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y ca-certificates curl tar
  elif command -v dnf >/dev/null 2>&1; then
    dnf install -y ca-certificates curl tar
  elif command -v yum >/dev/null 2>&1; then
    yum install -y ca-certificates curl tar
  elif command -v apk >/dev/null 2>&1; then
    apk add --no-cache ca-certificates curl tar
  else
    fail "curl/wget/python3 or tar is missing and no supported package manager was found"
  fi
}

if ! command -v tar >/dev/null 2>&1 || ! has_downloader; then
  install_dependencies || fail "dependency installation failed; check the target package repository and DNS"
fi
command -v tar >/dev/null 2>&1 || fail "tar is still unavailable after dependency installation"
has_downloader || fail "no downloader is available after dependency installation"

download_file() {
  source_url="$1"
  output_file="$2"
  if command -v curl >/dev/null 2>&1; then
    curl -fL "$source_url" -o "$output_file" --connect-timeout 20 --max-time 600 --retry 2 --retry-delay 3
  elif command -v wget >/dev/null 2>&1; then
    wget -O "$output_file" "$source_url" --timeout=30 --tries=3
  else
    python3 - "$source_url" "$output_file" <<'PY'
import shutil
import sys
import urllib.request

request = urllib.request.Request(sys.argv[1], headers={"User-Agent": "frp-panel-deployer/1.0"})
with urllib.request.urlopen(request, timeout=600) as response, open(sys.argv[2], "wb") as output:
    shutil.copyfileobj(response, output)
PY
  fi
}

WORKDIR=$(mktemp -d /tmp/frp-install.XXXXXX 2>/dev/null || echo "/tmp/frp-install-$$")
mkdir -p "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT
ARCHIVE="$WORKDIR/frp.tar.gz"
PACKAGE="frp_{{.Version}}_${OS}_${ARCH}"

echo "=== Downloading frp {{.Version}} ==="
downloaded=false
{{- range .DownloadURLs}}
if [ "$downloaded" = false ]; then
  URL="{{.}}/releases/download/v{{$.Version}}/${PACKAGE}.tar.gz"
  echo "Trying download source: $URL"
  rm -f "$ARCHIVE"
  if download_file "$URL" "$ARCHIVE" && [ -s "$ARCHIVE" ]; then
    downloaded=true
  else
    echo "Download source failed: $URL" >&2
  fi
fi
{{- end}}
[ "$downloaded" = true ] || fail "all FRP download sources failed"

echo "=== Verifying and extracting ==="
tar -tzf "$ARCHIVE" "$PACKAGE/frps" >/dev/null || fail "downloaded archive is invalid or does not match $PACKAGE"
tar -xzf "$ARCHIVE" -C "$WORKDIR" "$PACKAGE/frps"
chmod +x "$WORKDIR/$PACKAGE/frps"
INSTALLED_VERSION=$("$WORKDIR/$PACKAGE/frps" --version 2>&1) || fail "downloaded frps binary cannot run on this target"
echo "Downloaded frps version: $INSTALLED_VERSION"

echo "=== Installing atomically ==="
mkdir -p /opt/frp
cp "$WORKDIR/$PACKAGE/frps" /opt/frp/frps.new
chmod 0755 /opt/frp/frps.new
mv -f /opt/frp/frps.new /opt/frp/frps

echo "=== frps installed ==="
/opt/frp/frps --version
`

type InstallParams struct {
	Version      string
	DownloadURLs []string
}

var frpVersionPattern = regexp.MustCompile(`^\d+\.\d+\.\d+(?:[-.][0-9A-Za-z.]+)?$`)

func buildDownloadURLs(mirror string) []string {
	const official = "https://github.com/fatedier/frp"
	urls := make([]string, 0, 2)
	mirror = strings.TrimRight(strings.TrimSpace(mirror), "/")
	if mirror != "" && mirror != "https://github.com" {
		candidate := mirror + "/https://github.com/fatedier/frp"
		if parsed, err := url.Parse(candidate); err == nil && (parsed.Scheme == "http" || parsed.Scheme == "https") && parsed.Host != "" && !strings.ContainsAny(candidate, "\"' \t\r\n") {
			urls = append(urls, candidate)
		}
	}
	return append(urls, official)
}

func renderInstallScript(version, mirror string) (string, error) {
	if !frpVersionPattern.MatchString(version) {
		return "", fmt.Errorf("invalid FRP version %q", version)
	}
	tmpl, err := template.New("install").Parse(installScriptTemplate)
	if err != nil {
		return "", err
	}
	var script bytes.Buffer
	if err := tmpl.Execute(&script, InstallParams{Version: version, DownloadURLs: buildDownloadURLs(mirror)}); err != nil {
		return "", err
	}
	return script.String(), nil
}

func detectInitSystem(client *sshpool.Client) (string, error) {
	stdout, stderr, err := client.RunCommand("if command -v systemctl >/dev/null 2>&1; then echo systemd; elif command -v rc-service >/dev/null 2>&1 && command -v rc-update >/dev/null 2>&1; then echo openrc; else echo unsupported; exit 1; fi")
	if err != nil {
		return "", fmt.Errorf("detect service manager: %s %v", strings.TrimSpace(stderr), err)
	}
	return strings.TrimSpace(stdout), nil
}

func installAndStartFRPSService(client *sshpool.Client) error {
	initSystem, err := detectInitSystem(client)
	if err != nil {
		return err
	}

	var servicePath, serviceContent, serviceMode string
	var commands []string
	switch initSystem {
	case "systemd":
		servicePath = "/etc/systemd/system/frps.service"
		serviceContent = frpsServiceTemplate
		serviceMode = "0644"
		commands = []string{"systemctl daemon-reload", "systemctl enable frps", "systemctl restart frps", "sleep 2", "systemctl is-active frps"}
	case "openrc":
		servicePath = "/etc/init.d/frps"
		serviceContent = frpsOpenRCTemplate
		serviceMode = "0755"
		commands = []string{"rc-update add frps default", "rc-service frps restart || rc-service frps start", "sleep 2", "rc-service frps status"}
	default:
		return fmt.Errorf("unsupported service manager %q", initSystem)
	}

	if err := client.UploadFile([]byte(serviceContent), servicePath, serviceMode); err != nil {
		return fmt.Errorf("upload %s service: %w", initSystem, err)
	}
	for _, cmd := range commands {
		stdout, stderr, err := client.RunCommand(cmd)
		if err != nil {
			return fmt.Errorf("command %q failed: %s %s %v", cmd, strings.TrimSpace(stdout), strings.TrimSpace(stderr), err)
		}
	}
	return nil
}

func runFRPSServiceAction(client *sshpool.Client, action string) (string, string, error) {
	cmd := fmt.Sprintf("if command -v systemctl >/dev/null 2>&1; then systemctl %s frps; elif command -v rc-service >/dev/null 2>&1; then rc-service frps %s; else echo 'no supported service manager' >&2; exit 1; fi", action, action)
	return client.RunCommand(cmd)
}

func normalizeAgentURL(panelAddr string) (string, error) {
	panelAddr = strings.TrimSpace(panelAddr)
	if !strings.Contains(panelAddr, "://") {
		panelAddr = "http://" + panelAddr
	}
	parsed, err := url.Parse(panelAddr)
	if err != nil || (parsed.Scheme != "http" && parsed.Scheme != "https") || parsed.Host == "" || parsed.User != nil {
		return "", fmt.Errorf("invalid panel address %q", panelAddr)
	}
	parsed.Path = ""
	parsed.RawPath = ""
	parsed.RawQuery = ""
	parsed.Fragment = ""
	origin := strings.TrimRight(parsed.String(), "/")
	if strings.ContainsAny(origin, "\"'`$;&|()<> 	\r\n") {
		return "", fmt.Errorf("unsafe panel address %q", panelAddr)
	}
	return origin, nil
}

func downloadAgent(client *sshpool.Client, panelAddr string) error {
	origin, err := normalizeAgentURL(panelAddr)
	if err != nil {
		return err
	}
	agentURL := origin + "/agent"
	cmd := fmt.Sprintf(`mkdir -p /opt/frp-panel
if command -v curl >/dev/null 2>&1; then
  curl -fsSL -o /opt/frp-panel/agent '%s' --connect-timeout 30 --max-time 120 --retry 3
elif command -v wget >/dev/null 2>&1; then
  wget -O /opt/frp-panel/agent '%s' --timeout=30 --tries=3
elif command -v python3 >/dev/null 2>&1; then
  python3 -c "import urllib.request; urllib.request.urlretrieve('%s', '/opt/frp-panel/agent')"
else
  echo 'no downloader available for monitoring agent' >&2
  exit 1
fi
test -s /opt/frp-panel/agent && chmod 0755 /opt/frp-panel/agent`, agentURL, agentURL, agentURL)
	stdout, stderr, err := client.RunCommand(cmd)
	if err != nil {
		return fmt.Errorf("download agent: %s %s %v", strings.TrimSpace(stdout), strings.TrimSpace(stderr), err)
	}
	return nil
}

func installAndStartAgentService(client *sshpool.Client, panelAddr string, serverID uint, apiKey string) error {
	origin, err := normalizeAgentURL(panelAddr)
	if err != nil {
		return err
	}
	initSystem, err := detectInitSystem(client)
	if err != nil {
		return err
	}

	systemdContent := fmt.Sprintf(`[Unit]
Description=frp-panel agent
After=network.target

[Service]
Type=simple
ExecStart=/opt/frp-panel/agent -panel %s -server %d -key %s -interval 5
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
`, origin, serverID, apiKey)
	openrcContent := fmt.Sprintf(`#!/sbin/openrc-run
name="frp-panel agent"
command="/opt/frp-panel/agent"
command_args="-panel %s -server %d -key %s -interval 5"
command_background="yes"
pidfile="/run/frp-panel-agent.pid"
output_log="/var/log/frp-panel-agent.log"
error_log="/var/log/frp-panel-agent.log"
depend() { need net; }
`, origin, serverID, apiKey)

	var path, content, mode string
	var commands []string
	if initSystem == "systemd" {
		path, content, mode = "/etc/systemd/system/frp-panel-agent.service", systemdContent, "0644"
		commands = []string{"systemctl daemon-reload", "systemctl enable frp-panel-agent", "systemctl restart frp-panel-agent", "systemctl is-active frp-panel-agent"}
	} else {
		path, content, mode = "/etc/init.d/frp-panel-agent", openrcContent, "0755"
		commands = []string{"rc-update add frp-panel-agent default", "rc-service frp-panel-agent restart || rc-service frp-panel-agent start", "rc-service frp-panel-agent status"}
	}
	if err := client.UploadFile([]byte(content), path, mode); err != nil {
		return err
	}
	for _, cmd := range commands {
		stdout, stderr, err := client.RunCommand(cmd)
		if err != nil {
			return fmt.Errorf("command %q failed: %s %s %v", cmd, strings.TrimSpace(stdout), strings.TrimSpace(stderr), err)
		}
	}
	return nil
}

func (d *Deployer) GetPluginWebhookURL() string {
	return d.pluginWebhookURL
}

func (d *Deployer) GetPanelPort() int {
	return d.panelPort
}

// SyncAgentEndpoints updates all deployed servers' agent services with the current panel address.
// Called at startup to ensure agents always point to the correct panel port.
func (d *Deployer) SyncAgentEndpoints() {
	if d.pluginWebhookURL == "" {
		return
	}

	panelAddr := strings.TrimPrefix(d.pluginWebhookURL, "http://")
	panelAddr = strings.TrimPrefix(panelAddr, "https://")
	if idx := strings.Index(panelAddr, "/"); idx > 0 {
		panelAddr = panelAddr[:idx]
	}
	if !strings.Contains(panelAddr, ":") {
		panelAddr += fmt.Sprintf(":%d", d.panelPort)
	}

	var servers []model.Server
	d.db.Where("agent_installed = ? AND deleted_at IS NULL", 1).Find(&servers)

	for _, server := range servers {
		client := sshpool.NewClient(server.IP, server.SSHPort, server.SSHUser, server.SSHPassword, server.SSHPrivateKey)
		if err := client.Connect(); err != nil {
			log.Printf("[Deployer] SyncAgent: cannot connect to %s: %v", server.IP, err)
			continue
		}

		if err := installAndStartAgentService(client, panelAddr, server.ID, server.AgentGRPCAddr); err != nil {
			log.Printf("[Deployer] SyncAgent: upload service failed for %s: %v", server.IP, err)
			client.Close()
			continue
		}

		log.Printf("[Deployer] SyncAgent: updated agent on %s (%s) -> panel %s", server.Name, server.IP, panelAddr)
		client.Close()
	}
}

func (d *Deployer) Deploy(server *model.Server, panelAddr string) error {
	log.Printf("[Deployer] Starting deployment for server %s (%s)", server.Name, server.IP)

	// Update status
	d.db.Model(server).Update("status", "installing")

	client := sshpool.NewClient(server.IP, server.SSHPort, server.SSHUser, server.SSHPassword, server.SSHPrivateKey)

	// Step 1: Test connection
	log.Printf("[Deployer] Testing SSH connection...")
	if err := client.TestConnection(); err != nil {
		d.setError(server, fmt.Sprintf("SSH connection failed: %v", err))
		return err
	}

	// Step 2: Get system info
	log.Printf("[Deployer] Detecting system info...")
	osName, arch, err := client.GetSystemInfo()
	if err != nil {
		d.setError(server, fmt.Sprintf("Failed to get system info: %v", err))
		return err
	}
	log.Printf("[Deployer] System: %s %s", osName, arch)

	// Step 3: Install frps via script
	log.Printf("[Deployer] Installing frps...")
	version := server.FrpVersion
	if version == "" {
		version = "0.68.0"
	}

	script, err := renderInstallScript(version, d.githubMirror)
	if err != nil {
		d.setError(server, fmt.Sprintf("Template error: %v", err))
		return err
	}

	stdout, stderr, err := client.RunCommand(script)
	if err != nil {
		details := strings.TrimSpace(strings.Join([]string{stdout, stderr}, "\n"))
		if len(details) > 4000 {
			details = details[len(details)-4000:]
		}
		d.setError(server, fmt.Sprintf("Install failed: %s (%v)", details, err))
		return err
	}

	// Step 4: Generate and upload frps.toml
	log.Printf("[Deployer] Generating frps config...")
	pluginSecret := server.PluginSecret
	if pluginSecret == "" {
		pluginSecret = hash.RandomString(32)
	}
	nodeToken := hash.RandomString(32)
	pluginAddr, pluginPath, err := buildPluginEndpoint(panelAddr, server.ID, pluginSecret)
	if err != nil {
		d.setError(server, fmt.Sprintf("Invalid plugin webhook URL: %v", err))
		return err
	}
	config := FrpsConfig{
		BindAddr:          "0.0.0.0",
		BindPort:          server.BindPort,
		Token:             nodeToken,
		VhostHTTPPort:     server.VhostHTTPPort,
		VhostHTTPSPort:    server.VhostHTTPSPort,
		DashboardAddr:     "0.0.0.0",
		DashboardPort:     server.DashboardPort,
		DashboardUser:     server.DashboardUser,
		DashboardPassword: server.DashboardPassword,
		PluginAddr:        pluginAddr,
		PluginPath:        pluginPath,
		MaxPoolCount:      10,
		LogFile:           "/var/log/frps.log",
	}

	configTmpl, err := template.New("frps").Parse(frpsTomlTemplate)
	if err != nil {
		d.setError(server, fmt.Sprintf("Config template error: %v", err))
		return err
	}

	var configBuf bytes.Buffer
	configTmpl.Execute(&configBuf, config)

	if err := client.UploadFile(configBuf.Bytes(), "/opt/frp/frps.toml", "0644"); err != nil {
		d.setError(server, fmt.Sprintf("Upload config failed: %v", err))
		return err
	}

	// Step 5-6: Install and start the native service.
	log.Printf("[Deployer] Starting frps service...")
	if err := installAndStartFRPSService(client); err != nil {
		d.setError(server, fmt.Sprintf("Service installation failed: %v", err))
		return err
	}

	// Step 7: Verify frps is running
	log.Printf("[Deployer] Verifying frps...")
	running, err := client.CheckPort(server.BindPort)
	if err != nil || !running {
		d.setError(server, "frps port not listening after start")
		return fmt.Errorf("frps port %d not listening", server.BindPort)
	}

	// Step 8: Update server status
	now := time.Now()
	d.db.Model(server).Updates(map[string]interface{}{
		"status":              "running",
		"frp_version":         version,
		"last_heartbeat":      &now,
		"error_msg":           "",
		"token":               nodeToken,
		"plugin_secret":       pluginSecret,
		"plugin_auth_enabled": true,
		"plugin_webhook_addr": pluginAddr,
		"plugin_webhook_path": pluginPath,
	})

	// Step 9: Install agent for metrics reporting
	log.Printf("[Deployer] Installing agent...")
	if err := d.installAgent(server, client); err != nil {
		log.Printf("[Deployer] Warning: Failed to install agent: %v", err)
		// Don't fail deployment for agent installation failure
	}

	// Store SSH client in pool
	poolKey := fmt.Sprintf("%d", server.ID)
	d.pool.Set(poolKey, client)

	log.Printf("[Deployer] Deployment successful for server %s", server.Name)
	return nil
}

func buildPluginEndpoint(rawURL string, serverID uint, pluginSecret string) (string, string, error) {
	rawURL = strings.TrimSpace(rawURL)
	if !strings.Contains(rawURL, "://") {
		rawURL = "https://" + rawURL
	}
	u, err := url.Parse(rawURL)
	if err != nil || u.Host == "" || u.User != nil || (u.Scheme != "http" && u.Scheme != "https") {
		return "", "", fmt.Errorf("invalid webhook URL")
	}
	basePath := strings.TrimRight(u.EscapedPath(), "/")
	if basePath == "" {
		basePath = "/api/plugin/webhook"
	}
	path := fmt.Sprintf("%s/%d/%s", basePath, serverID, url.PathEscape(pluginSecret))
	return u.Scheme + "://" + u.Host, path, nil
}

func (d *Deployer) ExpectedPluginEndpoint(panelAddr string, server *model.Server) (string, string, error) {
	if server.PluginSecret == "" {
		return "", "", fmt.Errorf("node plugin secret is missing")
	}
	if strings.TrimSpace(panelAddr) == "" {
		panelAddr = d.pluginWebhookURL
	}
	if strings.TrimSpace(panelAddr) == "" {
		panelAddr = fmt.Sprintf("http://localhost:%d", d.panelPort)
	}
	return buildPluginEndpoint(panelAddr, server.ID, server.PluginSecret)
}

func (d *Deployer) PluginEndpointMatches(panelAddr string, server *model.Server) (bool, string) {
	if !server.PluginAuthEnabled {
		return false, "该节点需要由管理员重新部署后才能生成安全配置"
	}
	expectedAddr, expectedPath, err := d.ExpectedPluginEndpoint(panelAddr, server)
	if err != nil {
		return false, "该节点安全配置不完整，请在后台重新部署节点"
	}
	if server.PluginWebhookAddr == "" || server.PluginWebhookPath == "" {
		return false, "该节点部署记录缺少插件端点，请在后台重新部署节点"
	}
	if server.PluginWebhookAddr != expectedAddr || server.PluginWebhookPath != expectedPath {
		return false, "面板访问地址已变化，请在后台重新部署该节点"
	}
	return true, ""
}

func (d *Deployer) installAgent(server *model.Server, client *sshpool.Client) error {
	// Extract panel host and port from webhook URL
	panelURL := d.pluginWebhookURL
	if panelURL == "" {
		return fmt.Errorf("panel URL not configured")
	}

	panelAddr := strings.TrimPrefix(panelURL, "http://")
	panelAddr = strings.TrimPrefix(panelAddr, "https://")
	if idx := strings.Index(panelAddr, "/"); idx > 0 {
		panelAddr = panelAddr[:idx]
	}
	panelHost := panelAddr
	panelPort := fmt.Sprintf("%d", d.panelPort)
	if idx := strings.Index(panelAddr, ":"); idx > 0 {
		panelHost = panelAddr[:idx]
		panelPort = panelAddr[idx+1:]
	}

	// Check if agent binary already exists
	_, _, checkErr := client.RunCommand("test -x /opt/frp-panel/agent")
	agentExists := checkErr == nil

	if !agentExists {
		if err := downloadAgent(client, panelAddr); err != nil {
			return err
		}
	}

	// Generate API key for agent authentication
	apiKey := fmt.Sprintf("agent-%s-%d", server.IP, time.Now().Unix())

	if err := installAndStartAgentService(client, fmt.Sprintf("%s:%s", panelHost, panelPort), server.ID, apiKey); err != nil {
		return err
	}

	// Update server agent status
	d.db.Model(server).Updates(map[string]interface{}{
		"agent_installed": true,
		"agent_grpc_addr": apiKey,
	})

	log.Printf("[Deployer] Agent installed for server %s", server.Name)
	return nil
}

func (d *Deployer) Restart(server *model.Server) error {
	client, err := d.getSSHClient(server)
	if err != nil {
		return err
	}

	_, stderr, err := runFRPSServiceAction(client, "restart")
	if err != nil {
		return fmt.Errorf("restart failed: %s %v", stderr, err)
	}

	d.db.Model(server).Update("status", "running")
	return nil
}

func (d *Deployer) Stop(server *model.Server) error {
	client, err := d.getSSHClient(server)
	if err != nil {
		return err
	}

	_, stderr, err := runFRPSServiceAction(client, "stop")
	if err != nil {
		return fmt.Errorf("stop failed: %s %v", stderr, err)
	}

	d.db.Model(server).Update("status", "stopped")
	return nil
}

func (d *Deployer) UpdateConfig(server *model.Server, configContent string, panelAddr string) error {
	client, err := d.getSSHClient(server)
	if err != nil {
		return err
	}

	// Upload new config
	if err := client.UploadFile([]byte(configContent), "/opt/frp/frps.toml", "0644"); err != nil {
		return fmt.Errorf("upload config failed: %v", err)
	}
	if err := d.db.Model(server).Update("plugin_auth_enabled", false).Error; err != nil {
		return fmt.Errorf("invalidate plugin auth state: %v", err)
	}

	// Restart frps
	_, stderr, err := runFRPSServiceAction(client, "restart")
	if err != nil {
		return fmt.Errorf("restart failed: %s %v", stderr, err)
	}

	return nil
}

func (d *Deployer) GetFrpsConfig(server *model.Server) (string, error) {
	client, err := d.getSSHClient(server)
	if err != nil {
		return "", err
	}

	data, err := client.DownloadFile("/opt/frp/frps.toml")
	if err != nil {
		return "", err
	}

	return string(data), nil
}

func (d *Deployer) GetFrpsLogs(server *model.Server, lines int) (string, error) {
	client, err := d.getSSHClient(server)
	if err != nil {
		return "", err
	}

	cmd := fmt.Sprintf("if command -v journalctl >/dev/null 2>&1; then journalctl -u frps --no-pager -n %d; else tail -n %d /var/log/frps-service.log; fi", lines, lines)
	stdout, _, err := client.RunCommand(cmd)
	if err != nil {
		// Fallback to log file
		stdout, _, err = client.RunCommand(fmt.Sprintf("tail -n %d /var/log/frps.log", lines))
		if err != nil {
			return "", err
		}
	}

	return stdout, nil
}

func (d *Deployer) Uninstall(server *model.Server) error {
	client, err := d.getSSHClient(server)
	if err != nil {
		return err
	}

	commands := []string{
		"if command -v systemctl >/dev/null 2>&1; then systemctl stop frps 2>/dev/null || true; systemctl disable frps 2>/dev/null || true; rm -f /etc/systemd/system/frps.service; systemctl daemon-reload; elif command -v rc-service >/dev/null 2>&1; then rc-service frps stop 2>/dev/null || true; rc-update del frps default 2>/dev/null || true; rm -f /etc/init.d/frps; fi",
		"rm -rf /opt/frp",
		"rm -f /var/log/frps.log",
	}

	for _, cmd := range commands {
		client.RunCommand(cmd) // ignore errors
	}

	d.db.Model(server).Updates(map[string]interface{}{
		"status":      "pending",
		"frp_version": "",
	})

	d.pool.Remove(fmt.Sprintf("%d", server.ID))
	return nil
}

func (d *Deployer) getSSHClient(server *model.Server) (*sshpool.Client, error) {
	poolKey := fmt.Sprintf("%d", server.ID)
	client := d.pool.Get(poolKey)
	if client != nil {
		return client, nil
	}

	client = sshpool.NewClient(server.IP, server.SSHPort, server.SSHUser, server.SSHPassword, server.SSHPrivateKey)
	if err := client.Connect(); err != nil {
		return nil, fmt.Errorf("SSH connect failed: %w", err)
	}
	d.pool.Set(poolKey, client)
	return client, nil
}

func (d *Deployer) setError(server *model.Server, msg string) {
	d.db.Model(server).Updates(map[string]interface{}{
		"status":    "error",
		"error_msg": msg,
	})
	log.Printf("[Deployer] Error for server %s: %s", server.Name, msg)
}

func (d *Deployer) InstallAgent(server *model.Server, panelAddr, apiKey string) error {
	client, err := d.getSSHClient(server)
	if err != nil {
		return err
	}

	// Check if agent binary already exists
	_, _, checkErr := client.RunCommand("test -x /opt/frp-panel/agent")
	agentExists := checkErr == nil

	if !agentExists {
		// Agent not installed — full install
		log.Printf("[Deployer] Agent not found on %s, downloading...", server.Name)

		if err := downloadAgent(client, panelAddr); err != nil {
			return err
		}
	} else {
		log.Printf("[Deployer] Agent already exists on %s, updating config only", server.Name)
	}

	if err := installAndStartAgentService(client, panelAddr, server.ID, apiKey); err != nil {
		return err
	}

	// Update server agent status
	d.db.Model(server).Updates(map[string]interface{}{
		"agent_installed": true,
		"agent_grpc_addr": apiKey,
	})

	log.Printf("[Deployer] Agent installed for server %s", server.Name)
	return nil
}
